name: Publish Package to npmjs
on:
  push:
    branches: [master]
    paths:
      - 'package.json'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        name: setup node
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Create .npmrc
        run: |
          touch .npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Publish
        run: npm publish --access public
