name: Publish new version

on:
  push:
    branches: ['master']

jobs:
  production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          npm install
          npm test

      - name: Start release pipeline
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish
